config/routes.rb
Rails.application.routes.draw do

  resources :examples
  concern :paginatable do
    get '(page/:page)', :action => :index, :on => :collection, :as => ''
  end

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'signup'  => 'users#new'
  resources :microposts,          only: [:index, :show, :new, :create, :destroy], :concerns => :paginatable
  resources :users do
    member do
      get :following, :followers
      resources :tracks,              only: [:index, :show, :create, :destroy]
    end
  end

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :relationships,       only: [:create, :destroy]

  root 'welcome#index', :concerns => :paginatable

end

app/views/layouts/_navigation.html.erb
<nav class="top-bar" data-topbar role="navigation"> 
<ul class="title-area"> 
<li class="name"> 
<h1 class="brand"><%=link_to "MixEgo", root_path %></h1> 
</li> 
<!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone --> 
<li class="toggle-topbar menu-icon">
<a href="#"><span></span></a>
</li> 
</ul> 
<section class="top-bar-section"> 
<!-- Right Nav Section --> 



<ul class="right"> 
  <% if logged_in? %>
    <li><%= link_to "Users", users_path %></li>
    <li class="has-dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        Account <b class="caret"></b>
      </a>
      <ul class="dropdown">
        <li>
          <%= link_to "Profile", current_user %>
        </li>
        <li>
          <%= link_to "Settings", edit_user_path(current_user) %>
        </li>
        <li class="divider">
        </li>
        <li class="active">
          <%= link_to "Logout", logout_path, method: "delete" %>
        </li>
      </ul>
    </li>
  <% else %>
    <li class="active">
      <%= link_to "Sign Up", signup_path %>
    </li>
  <% end %>
</ul> 
<!-- Left Nav Section --> 
<ul class="left"> 
<li>
<%= link_to "Home", root_path %>
</li> 
</ul> 
</section> 
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <div class="container">
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>

  </body>
</html>

app/views/layouts/frontpage.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag "frontpage" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
		
		
		</head>

  <body id="frontpage" class='<%= controller.controller_name %>'>
    <div class="container">
      <%= yield %>
    </div>


    <%= javascript_include_tag "frontpage" %>


  </body>
</html>